### PR TITLE
feat: rename new remote api action and add associated model class

### PR DESCRIPTION
**Pull request by msft-paulkim**
#### Is this adding or improving a _feature_ or fixing a _bug_?
Part of adding new remote API action to support MS workflow

#### What's the new behavior?
No new behavior at this moment

### Does this fix any issues or need any specific reviewers?

Fixes: #
Reviewers: @

### CODE REVIEW

**Comment by msft-paulkim** [comment]
> Why is this scoped down to only the name change and new types?
> I would expect to see work for using in SDK and displaying in UI and Webchat.

No scope change of work. I just would like to reduce size of PR to get early feedback.

**Comment by mattmazzola** [comment]
K, early feedback is it looks like appropriate changes, but they're incomplete changes don't want this feature scattered across 5 PRs, as it is this isn't a feature.

**Comment by mattmazzola** [comment]
Had thought the other day in regards to "reduce size of PR" wanted to make it aware. If you want the benefits of approval/feedback chunked in small PR's rather than big, then you can use feature branches instead of merging to master.

`pak/remote_api_action` is a generic name to become the feature banch.
Make copy of it in new branch which represents the current changes to models then reset the base as `master` and merge into that feature branch. Then repeat for consecutive phases UI, SDK, etc or whoever you choose to split it.

**Comment by msft-paulkim** [comment]
> Had thought the other day in regards to "reduce size of PR" wanted to make it aware. If you want the benefits of approval/feedback chunked in small PR's rather than big, then you can use feature branches instead of merging to master.
> 
> `pak/remote_api_action` is a generic name to become the feature branch.
> Make copy of it in new branch which represents the current changes to models then reset the base as `master` and merge into that feature branch. Then repeat for consecutive phases UI, SDK, etc or whoever you choose to split it.
> 
> Update: actually might be easier to simply create new base branch instead of renaming because then you can re-use this PR and update the target branch without git complexity.

Thank you for your suggestion. I've decided to push more commits into this PR. Will do a feature branch in the future.

**Comment by LarsLiden** [comment]
@msft-paulkim  - Is this a dead PR?  Can it be deleted.

**Pull request closed without merging**
